### ISSUE TITLE
Cannot find source files

### ISSUE THREAD

**Issue by IvannoVMP** [multifive/multicore#1]
Hi, i have a big issue with the VS project : 

http://puu.sh/pgMEs/3271c27146.png

More than 1100 errors ? Can i have a list of libs to install ?

Thank's

**Comment by 0x452** [comment]
Thats mean, that u don't install all of libraries, i will write instruction tomorrow.


Best wishes,
swiftSDK

**Comment by 0x452** [comment]
Now try instruction and then write here. :cookie:

**Comment by IvannoVMP** [comment]
Same problem ..

**Comment by IvannoVMP** [comment]
After a complet and fresh install just that -> http://puu.sh/polqD/57733a2a08.png
