### ISSUE TITLE
bootstrapper error

### ISSUE THREAD

**Issue by 0x452** [MultiFive/multicore#1]
fully complete bootstrapper

**Comment by froggz19** [comment]
![multifive_main](https://cloud.githubusercontent.com/assets/8935954/15630405/0bd27760-2542-11e6-9a73-224b8ea1c7e0.jpg)
![multifive_signingin](https://cloud.githubusercontent.com/assets/8935954/15630406/13db3406-2542-11e6-98dc-b5ff807d87c6.jpg)
![multifive_terminal](https://cloud.githubusercontent.com/assets/8935954/15630408/17f479d0-2542-11e6-850c-efd15664a095.jpg)

Progress... I'm glad someone tries to revive this project.

**Comment by 0x452** [comment]
@froggz19 we are making terminal, that should start soon

**Comment by 0x452** [comment]
**fixed**

**Comment by froggz19** [comment]
@0x452 wait, for real?
