### ISSUE TITLE
Namespace "tinyxml2" has no member "XML_NO_ERROR"

### ISSUE THREAD

**Issue by TouchMyRAM** [multifive/multicore#2]
Already mentioned this one in chat, but I'll put it here just to log it ;)

Line 37 is at the top of the image

![Image of Bug]
(https://i.gyazo.com/ab2f15177bff5efabd677fdd66bf7478.png)

**Comment by froggz19** [comment]
https://github.com/leethomason/tinyxml2/commit/8553625730abec2467044b0bb2898b7c4f1114a3

**Comment by TouchMyRAM** [comment]
I was wondering where the namespace had gone haha, thanks!

**Comment by TouchMyRAM** [comment]
It's looking better now, just got an error relating to schannel

![Image to Error 2]
(https://i.gyazo.com/6bbea033252aa52ca36444abfd8cc52d.png)
