### ISSUE TITLE
An Error (22) occurred while checking the bootstrapper version. 

### ISSUE THREAD

**Issue by BMMaster33** [MultiFive/multicore#2]
Went to compile the source, created the EXE and launched in dev mode (by making .exe.dev as seen on old gitlab) and got "An Error (22) occurred while checking the bootstrapper version. Check if http://multifive.org/upd/five is available in your web browser"
thx
https://i.gyazo.com/66d7ba8122c59960a791789c6817965e.png

**Comment by 0x452** [comment]
it must work 

    среда, 1 июня 2016 17:39 BMMaster33 <notifications@github.com> писал(а):
 

 Went to compile the source, created the EXE and launched in dev mode (by making .exe.dev as seen on old gitlab) and got "An Error (22) occurred while checking the bootstrapper version. Check if http://multifive.org/upd/five is available in your web browser"https://i.gyazo.com/66d7ba8122c59960a791789c6817965e.png—

**Comment by BMMaster33** [comment]
ill tell you what i've done so far from getting the source, let me know if i go wrong

1. got the ply tools as said in the txt under the tools folder
2. executed all prebuild cmd files (except premake5)
3. did the command "premake5.exe vs2015 --game=five"
4. Opened the .sln file in visual studio under the build folder and build it
5. took all compiled files from bin/five/debug folder and put them in seperate folder
6. added the cache files from the fiveM folder in the zip to the folder containing fivem.exe
7. copied fivem.exe and renamed to fivem.exe.dev
8. executed fivem.exe.dev via command prompt

**Comment by 0x452** [comment]
dont start via cmd start usual fivem.exe

it should work

**Comment by BMMaster33** [comment]
i just did that now, i have this error https://gyazo.com/cb90d4e1db5ede7227a941271d5a1cae

**Comment by BMMaster33** [comment]
Edit: I wasn't able to compile nui-resources.dll https://gyazo.com/8999d72565e8c1c415f5a37f660f2f13 could that effect it?

**Comment by 0x452** [comment]
delete ros-five from components.json

i will fix error with nui-res

**Comment by BMMaster33** [comment]
not a problem, thank you :+1:
