### ISSUE TITLE
Issue with gclient sync

### ISSUE THREAD

**Issue by IvannoVMP** [MultiFive/multicore#3]
When i perform gclient sync I get this error -> http://puu.sh/pd8IY/c53a7372a1.png

I have install MSBuild, and in variable PATH i have add this line -> C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild and depotlibs

**Comment by 0x452** [comment]
check installed vs with msbuild, u must to install that correctly

**Comment by IvannoVMP** [comment]
BuildTools_Full.exe install
depot-tools install with path variable install
MSbuild variable path variable install too

Where are the problem ?

**Comment by 0x452** [comment]
don't worry with that error, u can skip dat

**Comment by froggz19** [comment]
What if you run "%VS120COMNTOOLS%\..\..\vc\vcvarsall.bat" before gclient sync?

**Comment by 0x452** [comment]
@froggz19 u may use it but its not need so

**Comment by IvannoVMP** [comment]
Are you sure, because if i skip this error when i perform premake command i get :

http://puu.sh/pdaZ5/6c53cfb960.png

**Comment by 0x452** [comment]
labeling bug, thanks

**Comment by IvannoVMP** [comment]
I have corrected the problem, you need simply add tostring(..)

I don't know how to push but as soon as I find I do a commit.

**Comment by 0x452** [comment]
closed.

**Comment by IvannoVMP** [comment]
I cannot push, if you want the exact solution, let me know.
